// LIMES MS — Dashboard (multi-asset)
// Data files (generated by GitHub Actions):
//   data/<slug>_daily.json
//   data/<slug>_15m.json
// Assets list:
//   assets.json  (metadata)
//   tickers.json (list + aliases)

let chart = null;
let assetsIndex = null; // {symbols:Set, aliasToSymbol:Map, symbolToName:Map}
const DEFAULT_SYMBOL = "XAUUSD";

// ---------- helpers ----------
function safeSlug(sym) {
  // mirror fetch_assets.py safe_slug()
  return (sym || "")
    .trim()
    .toLowerCase()
    .replaceAll("^", "")
    .replaceAll("=", "")
    .replaceAll(".", "_");
}

function fmtNum(x, digits = 2) {
  if (x === null || x === undefined || Number.isNaN(x)) return "—";
  return Number(x).toLocaleString(undefined, { minimumFractionDigits: digits, maximumFractionDigits: digits });
}

function fmtInt(x) {
  if (x === null || x === undefined || Number.isNaN(x)) return "—";
  return Number(x).toLocaleString(undefined, { maximumFractionDigits: 0 });
}

function clamp(x, a, b) { return Math.max(a, Math.min(b, x)); }

function setThaiClock() {
  const el = document.getElementById("thaiClock");
  const now = new Date();
  const th = now.toLocaleString("th-TH", {
    timeZone: "Asia/Bangkok",
    year: "numeric", month: "short", day: "numeric",
    hour: "2-digit", minute: "2-digit"
  });
  el.textContent = `${th} (UTC+7)`;
}
setThaiClock();
setInterval(setThaiClock, 30_000);

async function fetchJson(url) {
  const res = await fetch(url, { cache: "no-store" });
  if (!res.ok) throw new Error(`HTTP ${res.status} for ${url}`);
  return await res.json();
}

function parseYahooTS(ts) {
  // Our JSON stores ISO strings (utc) or epoch seconds sometimes.
  // Return Date objects in Asia/Bangkok labels.
  if (typeof ts === "number") return new Date(ts * 1000);
  return new Date(ts);
}

function labelDM(d) {
  const day = String(d.getDate()).padStart(2, "0");
  const mo = String(d.getMonth() + 1).padStart(2, "0");
  return `${day}/${mo}`;
}

function labelHM(d) {
  const hh = String(d.getHours()).padStart(2, "0");
  const mm = String(d.getMinutes()).padStart(2, "0");
  return `${hh}:${mm}`;
}

function linearRegressionSlope(y) {
  // simple least squares slope vs index 0..n-1
  const n = y.length;
  if (n < 2) return 0;
  let sumX = 0, sumY = 0, sumXY = 0, sumXX = 0;
  for (let i = 0; i < n; i++) {
    sumX += i; sumY += y[i];
    sumXY += i * y[i];
    sumXX += i * i;
  }
  const denom = (n * sumXX - sumX * sumX);
  if (denom === 0) return 0;
  return (n * sumXY - sumX * sumY) / denom; // units: price per step
}

function mean(arr) { return arr.reduce((a,b)=>a+b,0) / (arr.length || 1); }
function stdev(arr) {
  if (arr.length < 2) return 0;
  const m = mean(arr);
  const v = arr.reduce((a,x)=>a + (x-m)*(x-m),0) / (arr.length - 1);
  return Math.sqrt(v);
}

// ---------- assets / autocomplete ----------
async function loadAssetsIndex() {
  if (assetsIndex) return assetsIndex;

  let tickers = null, assets = null;
  try { tickers = await fetchJson("tickers.json"); } catch {}
  try { assets = await fetchJson("assets.json"); } catch {}

  const symbols = new Set();
  const aliasToSymbol = new Map();
  const symbolToName = new Map();

  if (Array.isArray(assets)) {
    for (const a of assets) {
      if (a && a.symbol) {
        symbols.add(a.symbol.toUpperCase());
        if (a.name) symbolToName.set(a.symbol.toUpperCase(), a.name);
        if (a.aliases && Array.isArray(a.aliases)) {
          for (const al of a.aliases) aliasToSymbol.set(String(al).toUpperCase(), a.symbol.toUpperCase());
        }
      }
    }
  }

  if (tickers && typeof tickers === "object") {
    if (Array.isArray(tickers.symbols)) {
      for (const s of tickers.symbols) symbols.add(String(s).toUpperCase());
    }
    if (Array.isArray(tickers.tickers)) {
      for (const s of tickers.tickers) symbols.add(String(s).toUpperCase());
    }
    if (tickers.aliases && typeof tickers.aliases === "object") {
      for (const [k,v] of Object.entries(tickers.aliases)) {
        aliasToSymbol.set(String(k).toUpperCase(), String(v).toUpperCase());
      }
    }
  }

  // a few safe convenience aliases
  aliasToSymbol.set("MAG7", "MAGS");   // Roundhill Magnificent Seven ETF (if available)
  aliasToSymbol.set("MAGY", "MAGS");

  assetsIndex = { symbols, aliasToSymbol, symbolToName };
  populateDatalist(assetsIndex);
  return assetsIndex;
}

function populateDatalist(idx) {
  const dl = document.getElementById("tickerList");
  if (!dl) return;
  dl.innerHTML = "";

  // show symbols with optional names
  const syms = Array.from(idx.symbols).sort((a,b)=>a.localeCompare(b));
  for (const s of syms) {
    const opt = document.createElement("option");
    const nm = idx.symbolToName.get(s);
    opt.value = s;
    opt.label = nm ? `${s} — ${nm}` : s;
    dl.appendChild(opt);
  }
}

function resolveSymbol(input) {
  const raw = (input || "").trim();
  if (!raw) return DEFAULT_SYMBOL;
  const up = raw.toUpperCase();

  const idx = assetsIndex;
  if (idx?.aliasToSymbol?.has(up)) return idx.aliasToSymbol.get(up);
  // allow user typing PTT.BK but files are ptt_bk; symbol stays as PTT.BK
  return up;
}

// ---------- risk model ----------
function riskFromSlopePct(absSlopePctPerDay) {
  // User rule: near 0 (±5%) = low risk
  // 5–10 = medium-low, 10–20 = medium-high, >20 = high risk
  if (absSlopePctPerDay <= 5) return 0.8;
  if (absSlopePctPerDay <= 10) return 1.8;
  if (absSlopePctPerDay <= 20) return 3.2;
  return 5.0;
}

function riskFromZ(absZ) {
  // z roughly tells band position; >2 is outside 2σ
  if (absZ <= 0.5) return 0.2;
  if (absZ <= 1.0) return 0.6;
  if (absZ <= 2.0) return 1.4;
  return 2.2;
}

function intradayMonitor(close15) {
  // returns array windows with pct change and risk flags
  const windows = [15,30,60,90,120]; // minutes
  const out = [];
  if (!close15 || close15.length < 3) return out;

  const latest = close15[close15.length - 1];
  for (const w of windows) {
    const step = Math.round(w / 15);
    if (close15.length - 1 - step < 0) continue;
    const prev = close15[close15.length - 1 - step];
    const pct = ((latest - prev) / prev) * 100;

    // flag rule: sharp negative move triggers high risk
    let flag = "";
    if (pct <= -1.2) flag = "HIGH";
    else if (pct <= -0.6) flag = "WATCH";
    else if (pct >= 1.2) flag = "HOT";
    else flag = "OK";

    out.push({ windowMin: w, pct, flag });
  }
  return out;
}

function extraRiskFromMonitor(mon) {
  // use worst negative window
  let worst = 0;
  for (const r of mon) {
    if (r.flag === "HIGH") worst = Math.max(worst, 2.2);
    else if (r.flag === "WATCH") worst = Math.max(worst, 1.2);
  }
  return worst;
}

function adviceFromState(state, slopePctPerDay, z, monitor) {
  // simple, explainable rules
  const worstNeg = Math.min(...monitor.map(r => r.pct));
  const hasHigh = monitor.some(r => r.flag === "HIGH");
  if (hasHigh && worstNeg < -1.2) return { tag: "HOLD", text: "Intraday momentum is sharply negative across multiple windows. Consider waiting for stabilization (or tighten risk controls) before adding exposure." };

  if (state === "HIGH RISK") return { tag: "HOLD", text: "Overall volatility / momentum is extreme. Avoid increasing position size until risk cools down." };
  if (slopePctPerDay < -5 && z < -0.5) return { tag: "SELL", text: "Downtrend confirmed (negative slope) and price is below the midline. Risk is tilted to the downside." };
  if (slopePctPerDay > 5 && z > -0.5) return { tag: "BUY", text: "Uptrend (positive slope) with price holding near/above midline. Risk looks manageable." };

  return { tag: "HOLD", text: "Mixed signals. Maintain position sizing and wait for a clearer trend confirmation." };
}

function stateFromRisk(riskScore) {
  if (riskScore >= 4.0) return "HIGH RISK";
  if (riskScore >= 2.2) return "WATCH";
  return "BUY";
}

// ---------- chart ----------
function makeChart(dates, price, mid, upper, lower, todayIdx) {
  const ctx = document.getElementById("chart").getContext("2d");

  if (chart) chart.destroy();

  const yMin = Math.min(...lower.filter(x => Number.isFinite(x)));
  const yMax = Math.max(...upper.filter(x => Number.isFinite(x)));
  const pad = (yMax - yMin) * 0.10;

  chart = new Chart(ctx, {
    type: "line",
    data: {
      labels: dates,
      datasets: [
        { label: "Upper", data: upper, borderColor: "#5a7aa6", borderWidth: 2, pointRadius: 0, tension: 0.25 },
        { label: "Lower", data: lower, borderColor: "#5a7aa6", borderWidth: 2, pointRadius: 0, tension: 0.25 },
        { label: "Phase / Mid (MA3)", data: mid, borderColor: "#8fd1ff", borderWidth: 2, pointRadius: 0, borderDash: [4,4], tension: 0.25 },
        { label: "Price", data: price, borderColor: "#f3b23c", borderWidth: 3, pointRadius: 2, pointHoverRadius: 4, tension: 0.25 },
      ]
    },
    options: {
      responsive: true,
      maintainAspectRatio: false,
      plugins: {
        legend: { display: false },
        tooltip: { mode: "index", intersect: false }
      },
      interaction: { mode: "index", intersect: false },
      scales: {
        x: {
          grid: { color: "rgba(255,255,255,0.06)" },
          ticks: { color: "rgba(231,238,252,0.65)", maxRotation: 0, autoSkip: true, maxTicksLimit: 8 }
        },
        y: {
          grid: { color: "rgba(255,255,255,0.06)" },
          ticks: { color: "rgba(231,238,252,0.65)" },
          suggestedMin: yMin - pad,
          suggestedMax: yMax + pad
        }
      }
    }
  });
}

// ---------- main load ----------
async function loadSymbol(symInput) {
  await loadAssetsIndex();
  const symbol = resolveSymbol(symInput);
  const slug = safeSlug(symbol);

  const titleSymbol = document.getElementById("titleSymbol");
  titleSymbol.textContent = symbol;

  // load data
  let daily, m15;
  try {
    daily = await fetchJson(`data/${slug}_daily.json`);
    m15 = await fetchJson(`data/${slug}_15m.json`);
  } catch (e) {
    alert(`ข้อมูลไม่พอสำหรับ ${symbol} (JSON ยังว่าง/สั้นเกินไป)\n\n${e.message}`);
    return;
  }

  if (!Array.isArray(daily) || daily.length < 20) {
    alert(`ข้อมูล Daily ไม่พอสำหรับ ${symbol}`);
    return;
  }

  // normalize daily
  const dDates = daily.map(r => labelDM(parseYahooTS(r.t)));
  const dClose = daily.map(r => Number(r.c)).filter(x => Number.isFinite(x));

  // rolling mid (MA3) and bands (±2σ on last 14)
  const mid = [];
  const upper = [];
  const lower = [];
  const winSigma = 14;

  for (let i = 0; i < dClose.length; i++) {
    const ma3 = mean(dClose.slice(Math.max(0, i-2), i+1));
    mid.push(ma3);

    const start = Math.max(0, i - winSigma + 1);
    const seg = dClose.slice(start, i+1);
    const sd = stdev(seg);
    upper.push(ma3 + 2*sd);
    lower.push(ma3 - 2*sd);
  }

  // slope on last 14 closes (price per day step)
  const look = Math.min(14, dClose.length);
  const slope = linearRegressionSlope(dClose.slice(-look)); // price per day-step
  const lastDaily = dClose[dClose.length - 1];
  const slopePctPerDay = (slope / lastDaily) * 100; // %
  const absSlopePctPerDay = Math.abs(slopePctPerDay);

  // z-score: position vs mid and sigma at last point
  const lastMid = mid[mid.length - 1];
  const lastSigma = (upper[upper.length - 1] - lastMid) / 2 || 0;
  const z = lastSigma > 0 ? (lastDaily - lastMid) / lastSigma : 0;

  // 15m values
  const close15 = Array.isArray(m15) ? m15.map(r => Number(r.c)).filter(x => Number.isFinite(x)) : [];
  const latest15 = close15.length ? close15[close15.length - 1] : lastDaily;

  // forecast (+1D): simple extrapolation of slope
  const fc1d = lastDaily + slope * 1;

  // monitor windows
  const mon = intradayMonitor(close15);
  const extraMonRisk = extraRiskFromMonitor(mon);

  // overall risk score (0..5)
  let score = 0;
  score += riskFromSlopePct(absSlopePctPerDay);
  score += riskFromZ(Math.abs(z));
  score += extraMonRisk;
  score = clamp(score, 0, 5);

  const state = stateFromRisk(score);

  // advice
  const advice = adviceFromState(state, slopePctPerDay, z, mon);

  // UI updates
  updatePanels({
    symbol,
    day0: daily[0]?.t ? labelDM(parseYahooTS(daily[0].t)) : "—",
    latest15,
    fc1d,
    slopePctPerDay,
    score,
    z,
    state,
    advice,
    mon,
    lastUpdate: m15?.length ? parseYahooTS(m15[m15.length - 1].t) : new Date()
  });

  // chart draw
  makeChart(dDates, dClose, mid, upper, lower, dClose.length - 1);
}

function updatePanels(x) {
  // state badge
  const badge = document.getElementById("stateBadge");
  badge.textContent = x.state;
  badge.classList.remove("buy","watch","high","hiFlash");
  if (x.state === "HIGH RISK") { badge.classList.add("high","hiFlash"); }
  else if (x.state === "WATCH") badge.classList.add("watch");
  else badge.classList.add("buy");

  // numbers
  document.getElementById("day0").textContent = x.day0;
  document.getElementById("latest15").textContent = fmtNum(x.latest15, 2);
  document.getElementById("fc1d").textContent = fmtNum(x.fc1d, 2);
  document.getElementById("slope").textContent = `${x.slopePctPerDay >= 0 ? "+" : ""}${fmtNum(x.slopePctPerDay, 2)}%/day`;
  document.getElementById("riskScoreText").textContent = `${fmtNum(x.score, 2)}/5`;

  // meter width
  const meter = document.getElementById("riskMeter");
  meter.style.width = `${clamp((x.score/5)*100, 0, 100)}%`;

  // z chip
  const zChip = document.getElementById("zChip");
  zChip.textContent = `z=${fmtNum(x.z, 2)}`;

  // advice
  const tag = document.getElementById("adviceTag");
  tag.textContent = x.advice.tag;
  tag.style.color = (x.advice.tag === "BUY") ? "var(--ok)" : (x.advice.tag === "SELL" ? "var(--bad)" : "var(--warn)");
  document.getElementById("adviceText").textContent = x.advice.text;

  // monitor table
  const table = document.getElementById("monitorTable");
  // remove old rows (keep 3 header cells)
  while (table.children.length > 3) table.removeChild(table.lastChild);
  for (const r of x.mon) {
    const w = document.createElement("div"); w.textContent = `${r.windowMin}m`;
    const d = document.createElement("div"); d.textContent = `${r.pct >= 0 ? "+" : ""}${fmtNum(r.pct, 2)}%`;
    const f = document.createElement("div"); f.innerHTML = `<span class="chip">${r.flag}</span>`;
    table.appendChild(w); table.appendChild(d); table.appendChild(f);
  }

  // bottom pill
  const pill = document.getElementById("statusPill");
  pill.style.display = "flex";
  const pillState = document.getElementById("pillState");
  pillState.textContent = x.state;
  pillState.classList.remove("buy","watch","high","hiFlash");
  if (x.state === "HIGH RISK") { pillState.classList.add("high","hiFlash"); }
  else if (x.state === "WATCH") pillState.classList.add("watch");
  else pillState.classList.add("buy");

  document.getElementById("pillLine1").textContent = `${x.symbol} — ${x.advice.tag}`;
  document.getElementById("pillLine2").textContent = `Risk score: ${fmtNum(x.score, 2)}/5`;
  const th = x.lastUpdate.toLocaleString("th-TH", { timeZone:"Asia/Bangkok", hour:"2-digit", minute:"2-digit" });
  document.getElementById("pillLine3").textContent = `Latest update: ${th} (TH)`;
}

// ---------- wire up ----------
document.getElementById("loadBtn").addEventListener("click", () => {
  const val = document.getElementById("symbolInput").value;
  loadSymbol(val);
});

document.getElementById("symbolInput").addEventListener("keydown", (e) => {
  if (e.key === "Enter") {
    e.preventDefault();
    loadSymbol(document.getElementById("symbolInput").value);
  }
});

// initial load
(async () => {
  await loadAssetsIndex();
  document.getElementById("symbolInput").value = DEFAULT_SYMBOL;
  loadSymbol(DEFAULT_SYMBOL);
})();
